config/routes.rb
Rails.application.routes.draw do
  root'dialogues#index'
  resources :dialogues
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dialogue.rb
class Dialogue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dialogues_controller.rb
class DialoguesController < ApplicationController
  before_action :set_dialogue, only: [:show, :edit, :update, :destroy]

  # GET /dialogues
  # GET /dialogues.json
  def index
    @dialogues = Dialogue.all
  end

  # GET /dialogues/1
  # GET /dialogues/1.json
  def show
  end

  # GET /dialogues/new
  def new
    @dialogue = Dialogue.new
  end

  # GET /dialogues/1/edit
  def edit
  end

  # POST /dialogues
  # POST /dialogues.json
  def create
    @dialogue = Dialogue.new(dialogue_params)

    respond_to do |format|
      if @dialogue.save
        format.html { redirect_to @dialogue, notice: 'Dialogue was successfully created.' }
        format.json { render :show, status: :created, location: @dialogue }
      else
        format.html { render :new }
        format.json { render json: @dialogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dialogues/1
  # PATCH/PUT /dialogues/1.json
  def update
    respond_to do |format|
      if @dialogue.update(dialogue_params)
        format.html { redirect_to @dialogue, notice: 'Dialogue was successfully updated.' }
        format.json { render :show, status: :ok, location: @dialogue }
      else
        format.html { render :edit }
        format.json { render json: @dialogue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dialogues/1
  # DELETE /dialogues/1.json
  def destroy
    @dialogue.destroy
    respond_to do |format|
      format.html { redirect_to dialogues_url, notice: 'Dialogue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dialogue
      @dialogue = Dialogue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dialogue_params
      params.require(:dialogue).permit(:title, :stirng)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dialogues_helper.rb
module DialoguesHelper
end

app/views/dialogues/_form.html.erb
<%= form_for(dialogue) do |f| %>
  <% if dialogue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dialogue.errors.count, "error") %> prohibited this dialogue from being saved:</h2>

      <ul>
      <% dialogue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :stirng %>
    <%= f.text_field :stirng %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dialogues/edit.html.erb
<h1>Editing Dialogue</h1>

<%= render 'form', dialogue: @dialogue %>

<%= link_to 'Show', @dialogue %> |
<%= link_to 'Back', dialogues_path %>

app/views/dialogues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dialogues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Stirng</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dialogues.each do |dialogue| %>
      <tr>
        <td><%= dialogue.title %></td>
        <td><%= dialogue.stirng %></td>
        <td><%= link_to 'Show', dialogue %></td>
        <td><%= link_to 'Edit', edit_dialogue_path(dialogue) %></td>
        <td><%= link_to 'Destroy', dialogue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dialogue', new_dialogue_path %>

app/views/dialogues/new.html.erb
<h1>New Dialogue</h1>

<%= render 'form', dialogue: @dialogue %>

<%= link_to 'Back', dialogues_path %>

app/views/dialogues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dialogue.title %>
</p>

<p>
  <strong>Stirng:</strong>
  <%= @dialogue.stirng %>
</p>

<%= link_to 'Edit', edit_dialogue_path(@dialogue) %> |
<%= link_to 'Back', dialogues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>